### ISSUE TITLE
Very specific settings allowed the extension to work somewhat as intended

### ISSUE THREAD

**Issue by frctlys** [AmigaAbattoir/CSharp.novaextension#2]
Hello there! First, thank you so much for working on this project, and I'd be happy to help to the best of my ability!

Second, I thought it would be worth illuminating how I was able to make this extension work at all on my computer.
I have an M1 Pro Macbook Pro, for context.

I had to turn off Autodetect Unity, ensure that I had both Mono and Dotnet 7 installed, then I pointed in the extension settings directly to my Mono.framework version, and my Dotnet SDK path in both locations where I was able to do so, and finally I kept Use Modern Dotnet checked.

With all of this done, I was only able to get the Intellisense and Syntax Highlighting to work if I opened the Unity Project root directory in Nova FIRST, and then started clicking files in the Unity project to be opened by Nova after already having the project open.

Hope this is helpful, I'm new to contributing to open source! Like I said, happy to contribute however I can!

**Comment by AmigaAbattoir** [comment]
One issue that I ran into was that I couldn't get Omnisharp to get the Intellisense/Syntax Highlighting, unless it is launched where a `.sln` file is. Part of that "Detect Unity" thing is to search for a solution file to ensure we launch Omnisharp with a solution file.

Did you have any older versions of DotNet installed? What version of Unity are you using and what version of .NET is it set to use? I'm using older projects which are set to .NET 4, I haven't tried with newer versions.

**Comment by frctlys** [comment]
Hey there, sorry for the late response. The versions of DotNet I had installed were Mono and DotNet7, and I was using the Unity LTS version which I believe was 2022.3.9f1. Hope that helps!

**Comment by AmigaAbattoir** [comment]
Marking as closed now that V0.4.3. As part of the requirements now state that you need to have a complete install of Mono and a .NET SDK in order for it to work. Also, Omnisharp is designed to only be able to provide completion and issues if it there is a project file with the code.
